### PR TITLE
Correct Bamboo Example

### PR DESCRIPTION
**Pull request by joelbyler**
Current example results in a syntax error, I believe this will fix that.

### CODE REVIEW

**Comment by danschultzer** [comment]
Thanks!

**Comment by joelbyler** [comment]
@danschultzer no problem, thanks for your work on this project.  FWIW I'm still having trouble setting up the mailer.  Should I expect that `PowEmailConfirmation` should be sending emails out upon registration or is that something I need to manually add to a controller callback?

**Comment by danschultzer** [comment]
If you are using custom controllers then you have to [add your own logic](https://hexdocs.pm/pow/custom_controllers.html#further-customization). Otherwise it should work if you follow the instructions here: https://github.com/danschultzer/pow#add-extensions-support

**Comment by joelbyler** [comment]
That was it, I had a custom controller callback...  thanks for the tip.  Again, awesome project!  👍

**Comment by joelbyler** [comment]
Ok, so followup question, is it possible to use both the built in extension callbacks (because they work really well), and some custom controller callback logic?  Do I need to write an extension to do this?  Is there a way to call those extension callbacks from a custom one?  Sorry if this is confusing but I have a small bit of custom logic that I'd like to continue using but would also love to reuse your extension callbacks.

**Comment by danschultzer** [comment]
Can you show me the custom logic you got? You may be able to add that logic with just plugs so you can use the default Pow controllers.

**Comment by joelbyler** [comment]
To give a more clear picture of my use case, I'm using postgis to store location data for users after they register, calling Google Maps geolocation service to get that info and store it in the database so I can search for nearby users later on.  We can take this conversation out of this PR though if you'd like?  Maybe log it as an issue?

**Comment by danschultzer** [comment]
Sure, please open an issue, and it would be great if you can post a sample for how the create action would look with postgis/google maps geolocation hook if you can so I can get a better idea why it needs to happen after registration.

**Comment by joelbyler** [comment]
Actually, looking at [this](https://github.com/danschultzer/pow/issues/279#issuecomment-533749781) some more and thinking that I can just handle this with an `after_registration_path` which can direct the user to a form where they can enter their address in separately.  This seems much more simple if I'm understanding that feature.

**Comment by danschultzer** [comment]
Yeah, that would work well. You can also add a plug checking if the user has the address filled out in case it's a requirement to finish registration, and always redirect them if it's missing.

**Comment by joelbyler** [comment]
Any chance you might have an example handy of how that plug idea would work?

**Comment by danschultzer** [comment]
Something like this could work:

```elixir
defmodule MyAppWeb.EnsureHasAddress do
  @moduledoc false

  import Plug.Conn, only: [halt: 1]

  alias MyAppWeb.Router.Helpers, as: Routes
  alias Phoenix.Controller
  alias Plug.Conn
  alias Pow.Plug

  @doc false
  @spec init(any()) :: any()
  def init(opts), do: opts

  @doc false
  @spec call(Conn.t(), any()) :: Conn.t()
  def call(conn, _opts) do
    conn
    |> Plug.current_user()
    |> completed_registration?()
    |> maybe_halt(conn)
  end

  defp completed_registration?(%{address: nil}), do: false
  defp completed_registration?(_any), do: true

  defp maybe_halt(true, conn), do: conn
  defp maybe_halt(_any, conn) do
    conn
    |> Controller.redirect(to: Routes.registration_path(conn, :address_prompt))
    |> halt()
  end
end
```

```elixir
defmodule MyAppWeb.Router do
  use MyAppWeb, :router
  # ...

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug MyAppWeb.EnsureHasAddress
  end

  scope "/admin", MyAppWeb do
    pipe_through [:browser, :admin]

    # ...
  end

  # ...
end
```

**Comment by joelbyler** [comment]
Wow @danschultzer this is super helpful, thanks so much for your help and patience!

**Comment by joepstender** [comment]
These examples should be documented instead of staying in the issue queue or pull request. There are quite a few of them already. Together with a nice index these could help people find their way more easily. For me as a novice examples work much better then condensed info in the code documentation which can be hard to grab. I’d be glad to help collect them.

**Comment by danschultzer** [comment]
@joepstender yeah, that would be great! I think this would be good to add to https://powauth.com/guides/

**Comment by joepstender** [comment]
Ok great, I will create issues on the pow_site repo for anything I find suitable. Perhaps label them "snippets" or something like that...

**Pull request merged**
