### PR TITLE
New guide for custom sessions and registration

### PR DESCRIPTION
**Pull request by abartier**
This is the first draft for a new guide. I'll continue editing it and improving it.

### CODE REVIEW

**Comment by danschultzer** [comment]
Looks good, thanks! I've some suggestions for how to make it more concise. I'm currently traveling but I'll get back to this asap 😄

**Comment by abartier** [comment]
Great, I'm looking forward for your feedback! 
Travel safe ;)

**Comment by danschultzer** [comment]
Sorry for the delay @abartier, this travel took pretty much all of my available time and first now I'm back at my desk. I've rebased your branch, and added some commits to make it more concise.

As you can see I prefer to keep the guides short and just handle one aspect, which in this case is custom controllers and routes. The accounts context and custom changeset is good too, but I think it would be better to have in a separate guide to not confuse the objective.

I've hopefully managed to keep your intention with the guide still 😄 what do you think?

**Comment by danschultzer** [comment]
Also, I've improved the code to ensure users are authenticated and not authenticated in the right routes.

**Comment by danschultzer** [comment]
This may be a good to add to the guide, to show how to use extensions with custom controllers: https://github.com/danschultzer/pow/issues/53#issuecomment-438459711

**Comment by abartier** [comment]
@danschultzer great improvements! I mentioned this was just a draft of the steps I took to achieve it. I think the refactored guide make more sense. 

For the extensions part, don't you think we should make another guide? This can help to keep the guides concise as you did before?

I did not play with the extensions yet. When I'll, I can draft another guide as I did for the custom controllers. What do you think?

I'll start two new Phoenix projects in the next weeks, I'll test Pow in "production conditions". I'll be able to give a better feedback too.

**Comment by danschultzer** [comment]
Yeah, it's probably out of scope since it would require some more thoughts on the setup of the custom controllers. A separate guide on how to utilize extensions in a custom setup is more appropriate.

This is good as it is so I'll merge it in 🚀  Thanks for your help @abartier!

**Comment by abartier** [comment]
You're welcome. 

I'll try to test extensions next week and play with it. Then I'll begin another draft for this new guide.

**Pull request merged**
