### PR TITLE
Fix path in PowResetPassword README.md

### PR DESCRIPTION
**Pull request by DiodonHystrix**

### CODE REVIEW

**Comment by DiodonHystrix** [comment]
Maybe we should add `<%= ... %>` too, for easier ctrl+c?

**Comment by DiodonHystrix** [comment]
Oh 🤦‍♂ It's correct, nvm. A bit confusing naming, though :p

**Comment by danschultzer** [comment]
Yeah I know. It’s because the extension is called `PowResetPassword` and the controller is called `ResetPasswordController` so the full alias becomes `pow_reset_password_reset_password`. Not pretty, but I couldn’t find a better option when I built the extension router logic 😅

**Comment by danschultzer** [comment]
I’m fine with adding `<%= ... %>` btw.

**Pull request closed without merging**
