### PR TITLE
Add API guide

### LINKED ISSUE #176: API integration guide
There's been a few issues with questions on how to integrate Pow with an API built in Phoenix: #170 #167 #153

A guide on API integration should be written. While I believe many would use absinthe, I think the guide should just focus on using plain Phoenix.

There may be some changes that can be made to Pow to make it as easy as Pow currently is for browser pipeline setup for API integration. However, I have a feeling that it's better to be explicit with routes for API so requiring the developer to add the individual routes rather than having a `pow_routes/0` or `pow_api_routes/0` macro. Sessions can be used as API keys, but it may be better to show how to use `Phoenix.Token` instead.

### PR DESCRIPTION
**Pull request by danschultzer**
Resolves #176

### CODE REVIEW

**Comment by popo63301** [comment]
Amazing ! 😍

**Comment by danschultzer** [comment]
@popo63301 🚀 feel free to test it out and comment! I haven't tested the code yet, but will do it soon (and I would like to add some copy-paste test modules too)

**Comment by popo63301** [comment]
Sure ! I'll try to give a try soon. I'm wondering though why the code is not part of the library itself rather than the API guide. Or maybe that's the next step?

**Comment by danschultzer** [comment]
Yeah, I attempt to limit the working parts in Pow as much as possible and instead just make it easy to customize. So the best way to go about this is first a guide, and then maybe take parts of that and implement into Pow to make it easier. However, for API I do believe it's better if the dev writes it out completely to have full control of how the API responses look.

**Comment by danschultzer** [comment]
Ok, I think it's ready now. I've added test modules, and tested it out myself 🚀

**Comment by popo63301** [comment]
Great ! Thanks for your amazing work Dan ! Pow is going to be the way to go for Phoenix authentication !  😎

**Pull request merged**
