### PR TITLE
Use provided schema name in printed instructions

### PR DESCRIPTION
**Pull request by DiodonHystrix**
I've noticed that printed instructions after running `mix pow.install` aren't correct if you provide schema name.

### CODE REVIEW

**Comment by danschultzer** [comment]
Oh yeah, this makes sense, thanks!

Let me just think if it makes sense to handle schema name in `pow.phoenix.install` mix task, or if it's better to let `pow.install` pass that configuration after it has run the ecto tasks. The docs should also be updated in the `pow.install` mix task to mention custom schema name.

**Comment by DiodonHystrix** [comment]
Could we also add that information to `README`? It's the first place that people look at and it's nice to know that you can customize the schema name(context), which is IMO very important.

Waiting for your decision regarding configuration and I'm gonna make proper adjustments :)

**Comment by danschultzer** [comment]
Yeah, it's a good point. But I think it's best to refer to the docs for that (like ecto/phoenix): https://hexdocs.pm/pow/Mix.Tasks.Pow.Install.html

The README is pretty big and I'm thinking of shorten it so it's easier to get through. At the same time I also want to highlight how flexible Pow is for developers who doesn't care enough to go through the docs yet. I definitely agree how information on the mix tasks in the README can help 😄

**Comment by danschultzer** [comment]
It was some messy setup I had created before. The schema defaults was set in four different mix tasks. So I went ahead and DRY'ed it all up, so it's now pulled from just one place!

**Comment by DiodonHystrix** [comment]
Well done :) Thanks for help. Should anything else be done here?

**Comment by danschultzer** [comment]
It’s ready, thanks!

**Pull request merged**
