### PR TITLE
Set @phoenix_routes  and unquote the opts

### PR DESCRIPTION
**Pull request by humancopy**
Adding to #199 

I've tested it and it works, no more duplicate routes and no warning 😄 

Let me know what you think, and if it's cool I can add some tests for the new code ...

### CODE REVIEW

**Comment by danschultzer** [comment]
I don't think `@before_compile` is needed, doesn't look like it does anything in this case 😄

Thanks for testing it, and fixing the missing `opts`! I'll setup a test in #199 that ensures the routes are indeed unique and then get it merged to master later today 🚀

**Comment by humancopy** [comment]
Without the `@before_compile` it was crashing for me saying that `@phoenix_routes` was not defined...

**Comment by danschultzer** [comment]
Oh, weird, `@phoenix_routes` should’ve been made available by the `Phoenix.Router` macro. I’ll test with a sample app here to see why it fails.

**Comment by humancopy** [comment]
Hmmmm strange I just double checked and you're right, the `@before_compile` is not needed, `@phoenix_routes` is already set. Wonder why it crashed for me before 🤷‍♂ 😄

**Pull request merged**
